server:
  port: 8080

spring:

  #RabbitMQ配置
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
#    publisher-returns: true #交换机路由队列确认机制，失败时是否回调
#    listener:
#      simple:
#        prefetch: 1 #消费者每次提取消息的数量，处理成功后在提取下一条，防止消息阻塞

  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qwe123


  mvc:
    view:
      suffix: .html

#  redis:
#    host: 127.0.0.1
#    port: 6379
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test

#  kafka:
#    # 指定kafka代理地址，可以多个
#    bootstrap-servers: 112.126.74.67:9092
#
#    # =========== producer
#    producer:
#      retries: 0
#      # 每次批量发送消息的数量
#      batch-size: 16384
#      buffer-memory: 33554432
#
#    # ========== consumer
#    consumer:
#      group-id: user-log-group
#      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval: 100


